[tool.poetry]
name = "calc-dpi-by-distance"
version = "0.1.0"
description = ""
authors = ["Wildiney Di Masi <wildiney@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
